Readme game instructions
Eshy10/Ruby-Tic-Tac-Toe pull request #5
Opened 2020-03-19 13:06 UTC by Eshy10

## Readme File containing instructions on how to play the game
- Added a Readme File
- The Readme File contains instructions on how to play and run the game

2020-03-19 18:49 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Eshy10 and @vzdrizhni :balloon: :lollipop: 

### You've done a great job with this project overall and using a good template for your Readme file :star: :star: there's a couple things to change so please address the comments I've left in your code :point_down: 

[OPTIONAL]

#### Behaviour

- [x] Your game lets players have empty names or the same name and when they do the game is giving them the same mark('X'), so let's add a validation for this to avoid ambiguity preventing the users to have the same name or set a default name when user's don't provide one. this wasn't pointed out in previous reviews but I strongly recommend to fix it:

![image](https://user-images.githubusercontent.com/52209067/77102828-150cb800-69df-11ea-9802-be3008979781.png)

- [x] Your game also stops working whenever a user try to pick an already taken cell and then try to pick the number 9 I think you also need a validation so the game doesn't stop working. again this wasn't pointed out in the last milestone but I strongly recommend to fix it:

![image](https://user-images.githubusercontent.com/52209067/77103200-a8de8400-69df-11ea-809c-4751b921161d.png)

### That's it, team! :raised_hands: 

### Please :pray: do the changes in your Readme file (and the optional changes or not) :woman_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy Coding! :rocket: 

Any questions? ask me on slak **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-03-19 18:49 UTC, euqueme commented on README.md
> +**This is an example of how you may give instructions on setting up your project locally.**
- [ ] kindly remove line #22 because it belongs to the Readme template you used but not to your project

2020-03-19 18:49 UTC, euqueme commented on README.md
> +- Clone the repository on your local machine
- [ ] Final user's don't need to clone the repo they can just download it, let's tell them how

2020-03-19 18:49 UTC, euqueme commented on README.md
> +- cd into the folder, find the bubble_sort file and open it
- [ ] bubble_sort is not part of your project, let's change this line

2020-03-19 18:49 UTC, euqueme commented on README.md
> +- Run bundle install.
- [ ] Final users don't need VSCode, or rubocop they only need to have ruby installed in their computers so let's put these instructions in a section for developers or contributors

2020-03-19 18:49 UTC, euqueme commented on README.md
> +- Run rubocop to fix linters errors
- [ ] let's also put the Run test section in a section for Developers or Contributors within your Readme file

2020-03-19 18:49 UTC, euqueme commented on README.md
> +Feel free to check the [issues page]().
- [ ] right now the issues page link leads to an empty page, add the URL within the parenthesis to the issues page link or remove it from the Readme file

2020-03-20 03:29 UTC, whiz25 requested changes
## Good Job
Your README looks good but we need to add rules for the game before we can merge.
- [ ] README file should explain the rules of the game. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone4/readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] add this change and send for another review

### Martin Afani

2020-03-20 06:48 UTC, Eshy10 commented
> ## Good Job
> Your README looks good but we need to add rules for the game before we can merge.
> 
> * [ ]  README file should explain the rules of the game. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone4/readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
> * [ ]  add this change and send for another review
> 
> ### Martin Afani

2020-03-20 07:01 UTC, Eshy10 commented
Instructions are in the readme file, please kindly check

2020-03-20 11:12 UTC, whiz25 approved these changes
## Hey @Eshy10  and @vzdrizhni 
Merge and proceed. Your README looks good.

### Martin Afani

2020-03-20 11:15 UTC, merged